# Generated by Django 4.0.5 on 2023-04-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HMC_Chaiman',
            new_name='HMC_Chairman',
        ),
    ]
