# Generated by Django 4.0.5 on 2023-04-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallmanage', '0002_rename_hmc_chaiman_hmc_chairman'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HMC_Chairman',
            new_name='HMCChairman',
        ),
    ]
