# Generated by Django 4.0.5 on 2023-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallmanage', '0003_rename_hmc_chairman_hmcchairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='_type',
            field=models.TextField(blank=True, choices=[('old', 'old'), ('new', 'new')], max_length=300, null=True),
        ),
    ]
